### ISSUE TITLE
Feature: rename `envs` to `dynenvs`

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator-go#30]
The builder takes an input `envs` to pass environment variables generated at build time (e.g., ldflags).
Static env variables are declared in the .slsa-goreleaser.yml file.

Shall we rename `envs` to `dynenvs`/`dyn_envs`/`dynamic_envs`?

**Comment by laurentsimon** [comment]
@asraa @joshuagl any feedback on this one?

Context: env variables are defined in the config file by a user. But env variables that need to be dynamically resolved at compile time (LDFLAGS, e.g. to retrieve the Git version) need to use this input:
```
uses: slsa-framework/slsa-github-generator-go/.github/workflows/builder.yml@main
    with:
      # Optional: only needed if using ldflags.
      env: "VERSION_LDFLAGS:${{needs.args.outputs.ldflags}}"
```

I''m suggesting we use `dynenv: "VERSION_LDFLAGS:${{needs.args.outputs.ldflags}}"` or something to this effect instead.

Any preference on the name?
